### ISSUE TITLE
It doesn't give me live updates of every UT sport score

### ISSUE THREAD

**Issue by johnluetz** [brandonforty2/UTDiscordBot#1]
How else am I supposed to follow sports while gaming??

**Comment by brandonforty2** [comment]
I see, I'm working on it right now

**Comment by brandonforty2** [comment]
Okay, I have added the ability to check the most important UT football game with ~score.  It is live on the UT Discord server.

**Comment by johnluetz** [comment]
Does not mention 'dicker the kicker' - please revise.

**Comment by brandonforty2** [comment]
"Dicker the Kicker was added to the master branch.  Itll be pushed out to the high power server that the bot runs on in the next update.
